insert into ingredients (name) values ('apple cider vinegarcarrot');
insert into ingredients (name) values ('tomato saucelima bean, broccoli');
insert into ingredients (name) values ('baconspaghetti');
insert into ingredients (name) values ('fishthyme');
insert into ingredients (name) values ('buttermilkpepper');
insert into ingredients (name) values ('appleketchup');
insert into ingredients (name) values ('porkginger');
insert into ingredients (name) values ('heavy creamshrimp');
insert into ingredients (name) values ('pimentosweet corn');
insert into ingredients (name) values ('salted butter,unsalted buttersoy sauce');
insert into ingredients (name) values ('goudaflour');
insert into ingredients (name) values ('swiss cheesestringed bean');
insert into ingredients (name) values ('waterbanana');
insert into ingredients (name) values ('duckmustard');
insert into ingredients (name) values ('whipped creamcauliflower, garlic');
insert into ingredients (name) values ('dried peachblackberry');
insert into ingredients (name) values ('skimmed milkscotch bonnet');
insert into ingredients (name) values ('turkeysalted mackerel');
insert into ingredients (name) values ('cheddar cheesesalmon');
insert into ingredients (name) values ('heavy creamsalmon');
insert into ingredients (name) values ('heavy creamwhite yam');
insert into ingredients (name) values ('non-fat milkangel hair pasta');
insert into ingredients (name) values ('vegetable oilsalted fish');
insert into ingredients (name) values ('whipped creampepper');
insert into ingredients (name) values (' sweet peppermaple syrup');
insert into ingredients (name) values ('blue cheesesalmon');
insert into ingredients (name) values ('evaporated milkshrimp');
insert into ingredients (name) values ('milk chocolatescotch bonnet');
insert into ingredients (name) values ('goudalobster');
insert into ingredients (name) values ('ricottayeast');
insert into ingredients (name) values ('sour cream, eggcassava');
insert into ingredients (name) values ('gooseparsley');
insert into ingredients (name) values ('applesalted mackerel');
insert into ingredients (name) values ('corn oilcabbage');
insert into ingredients (name) values ('non-fat milksalmon');
insert into ingredients (name) values ('lemon juicesesame oil');
insert into ingredients (name) values ('onionpassion fruit');
insert into ingredients (name) values ('vanilla extracttuna');
insert into ingredients (name) values (' sweet pepperred herring');
insert into ingredients (name) values ('dried pineapplecauliflower, garlic');
insert into ingredients (name) values ('parmesan cheeseminced beef');
insert into ingredients (name) values ('almondsoy bean');
insert into ingredients (name) values (' baking powderradish');
insert into ingredients (name) values ('turkeymacaroni');
insert into ingredients (name) values ('caramelpanko');
insert into ingredients (name) values ('wateroster sauce');
insert into ingredients (name) values ('monterey cheeseraisins');
insert into ingredients (name) values ('peanutcarrot');
insert into ingredients (name) values ('porkokra');
insert into ingredients (name) values ('almondwhite yam');
insert into ingredients (name) values (' baking powdercucumber');
insert into ingredients (name) values ('turkeyturnip');
insert into ingredients (name) values ('quailjam');
insert into ingredients (name) values ('plain yogurtwhite rice');
insert into ingredients (name) values ('glucoseyellow yam');
insert into ingredients (name) values ('vegetable oiljalapeno pepper');
insert into ingredients (name) values ('wheymustard');
insert into ingredients (name) values ('creamed cheesepepper');
insert into ingredients (name) values ('dried peachpenne pasta');
insert into ingredients (name) values ('gooseblackberry');
insert into ingredients (name) values ('plain yogurtkale');
insert into ingredients (name) values ('italian sausagepanko');
insert into ingredients (name) values ('turkeyhazelnut');
insert into ingredients (name) values ('dark chocolateparsley');
insert into ingredients (name) values ('vegetable oilginger');
insert into ingredients (name) values ('lime juicepanko');
insert into ingredients (name) values ('provolone cheesepeanut butter, almond butter');
insert into ingredients (name) values ('pepperoniturnip');
insert into ingredients (name) values ('whipped creamcabbage');
insert into ingredients (name) values ('applejalapeno pepper');
insert into ingredients (name) values ('cashewscotch bonnet');
insert into ingredients (name) values ('pineapplejam');
insert into ingredients (name) values ('turkey sausageyeast');
insert into ingredients (name) values ('chocolate chiplobster');
insert into ingredients (name) values ('ricottaplantain');
insert into ingredients (name) values ('heavy creamparsley');
insert into ingredients (name) values ('dark chocolatestringed bean');
insert into ingredients (name) values ('ricottaradish');
insert into ingredients (name) values ('full cream milksoy bean');
insert into ingredients (name) values ('egg whitesea salt');
insert into ingredients (name) values ('italian sausagered herring');
insert into ingredients (name) values ('whole milkmaple syrup');
insert into ingredients (name) values ('caramelbanana');
insert into ingredients (name) values ('vanilla extractturnip');
insert into ingredients (name) values ('lemon juicesalmon');
insert into ingredients (name) values ('plain yogurtscotch bonnet');
insert into ingredients (name) values ('egg whiteketchup');
insert into ingredients (name) values ('oliveginger');
insert into ingredients (name) values ('tomato saucemargarine');
insert into ingredients (name) values ('mozzarella cheesethyme');
insert into ingredients (name) values ('coconut oilraisins');
insert into ingredients (name) values ('peachbeef');
insert into ingredients (name) values ('watercorn');
insert into ingredients (name) values ('low-fat milkmustard');
insert into ingredients (name) values ('full cream milkcabbage');
insert into ingredients (name) values ('sweetened condensed milkradish');
insert into ingredients (name) values ('tomato saucehoney, cinnamon');
insert into ingredients (name) values ('apple cider vinegarpak choy');
insert into ingredients (name) values ('whole milkplantain');
insert into ingredients (name) values ('egg yolkradish');
